version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  detector:
    build: ./dectector
    environment:
      MQTT_HOST: mqtt
  extractor:
    build: ./extractor
    environment:
      MQTT_HOST: mqtt


